package com.wml.ssm.manage.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class CashUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.idcard
     *
     * @mbg.generated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.gender
     *
     * @mbg.generated
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.education
     *
     * @mbg.generated
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.marriage_status
     *
     * @mbg.generated
     */
    private Byte marriageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.nation
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.validity_term
     *
     * @mbg.generated
     */
    private String validityTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.issue_organization
     *
     * @mbg.generated
     */
    private String issueOrganization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.live_province
     *
     * @mbg.generated
     */
    private Long liveProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.live_city
     *
     * @mbg.generated
     */
    private Long liveCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.live_area
     *
     * @mbg.generated
     */
    private Long liveArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.live_address
     *
     * @mbg.generated
     */
    private String liveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.household_address
     *
     * @mbg.generated
     */
    private String householdAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.unit_name
     *
     * @mbg.generated
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.unit_province
     *
     * @mbg.generated
     */
    private Long unitProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.unit_city
     *
     * @mbg.generated
     */
    private Long unitCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.unit_area
     *
     * @mbg.generated
     */
    private Long unitArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.unit_address
     *
     * @mbg.generated
     */
    private String unitAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.unit_mobile
     *
     * @mbg.generated
     */
    private String unitMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.zm_score
     *
     * @mbg.generated
     */
    private String zmScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.zm_score_time
     *
     * @mbg.generated
     */
    private Date zmScoreTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.zm_open_id
     *
     * @mbg.generated
     */
    private String zmOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.authentication_flag
     *
     * @mbg.generated
     */
    private Byte authenticationFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.ocr_flag
     *
     * @mbg.generated
     */
    private Byte ocrFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.ocr_back_flag
     *
     * @mbg.generated
     */
    private Byte ocrBackFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.mobile_flag
     *
     * @mbg.generated
     */
    private Byte mobileFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.face_flag
     *
     * @mbg.generated
     */
    private Byte faceFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.face_score
     *
     * @mbg.generated
     */
    private String faceScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.online_duration
     *
     * @mbg.generated
     */
    private String onlineDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.operator_access_flag
     *
     * @mbg.generated
     */
    private Byte operatorAccessFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.account_flag
     *
     * @mbg.generated
     */
    private Byte accountFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.sign_fail_msg
     *
     * @mbg.generated
     */
    private String signFailMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.crawl_time
     *
     * @mbg.generated
     */
    private Date crawlTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.channel_code
     *
     * @mbg.generated
     */
    private String channelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_login_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_supplement_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsSupplementTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_authentication_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsAuthenticationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_operator_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsOperatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_face_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsFaceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_sign_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsSignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_apply_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsApplyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_auto_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsAutoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_obtain_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsObtainTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_loan_time
     *
     * @mbg.generated
     */
    private Date statisticsFirtsLoanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.statistics_firts_loan_amount
     *
     * @mbg.generated
     */
    private BigDecimal statisticsFirtsLoanAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.is_credit
     *
     * @mbg.generated
     */
    private Integer isCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.credit_amount
     *
     * @mbg.generated
     */
    private BigDecimal creditAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.first_credit_amount
     *
     * @mbg.generated
     */
    private BigDecimal firstCreditAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.is_enabled
     *
     * @mbg.generated
     */
    private Byte isEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.create_id
     *
     * @mbg.generated
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.modify_id
     *
     * @mbg.generated
     */
    private Long modifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.credit_time
     *
     * @mbg.generated
     */
    private Date creditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.zm_flag
     *
     * @mbg.generated
     */
    private Integer zmFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cash_user.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.id
     *
     * @return the value of cash_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.id
     *
     * @param id the value for cash_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.username
     *
     * @return the value of cash_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.username
     *
     * @param username the value for cash_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.mobile
     *
     * @return the value of cash_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.mobile
     *
     * @param mobile the value for cash_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.idcard
     *
     * @return the value of cash_user.idcard
     *
     * @mbg.generated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.idcard
     *
     * @param idcard the value for cash_user.idcard
     *
     * @mbg.generated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.gender
     *
     * @return the value of cash_user.gender
     *
     * @mbg.generated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.gender
     *
     * @param gender the value for cash_user.gender
     *
     * @mbg.generated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.age
     *
     * @return the value of cash_user.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.age
     *
     * @param age the value for cash_user.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.education
     *
     * @return the value of cash_user.education
     *
     * @mbg.generated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.education
     *
     * @param education the value for cash_user.education
     *
     * @mbg.generated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.marriage_status
     *
     * @return the value of cash_user.marriage_status
     *
     * @mbg.generated
     */
    public Byte getMarriageStatus() {
        return marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.marriage_status
     *
     * @param marriageStatus the value for cash_user.marriage_status
     *
     * @mbg.generated
     */
    public void setMarriageStatus(Byte marriageStatus) {
        this.marriageStatus = marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.nation
     *
     * @return the value of cash_user.nation
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.nation
     *
     * @param nation the value for cash_user.nation
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.validity_term
     *
     * @return the value of cash_user.validity_term
     *
     * @mbg.generated
     */
    public String getValidityTerm() {
        return validityTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.validity_term
     *
     * @param validityTerm the value for cash_user.validity_term
     *
     * @mbg.generated
     */
    public void setValidityTerm(String validityTerm) {
        this.validityTerm = validityTerm == null ? null : validityTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.issue_organization
     *
     * @return the value of cash_user.issue_organization
     *
     * @mbg.generated
     */
    public String getIssueOrganization() {
        return issueOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.issue_organization
     *
     * @param issueOrganization the value for cash_user.issue_organization
     *
     * @mbg.generated
     */
    public void setIssueOrganization(String issueOrganization) {
        this.issueOrganization = issueOrganization == null ? null : issueOrganization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.live_province
     *
     * @return the value of cash_user.live_province
     *
     * @mbg.generated
     */
    public Long getLiveProvince() {
        return liveProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.live_province
     *
     * @param liveProvince the value for cash_user.live_province
     *
     * @mbg.generated
     */
    public void setLiveProvince(Long liveProvince) {
        this.liveProvince = liveProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.live_city
     *
     * @return the value of cash_user.live_city
     *
     * @mbg.generated
     */
    public Long getLiveCity() {
        return liveCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.live_city
     *
     * @param liveCity the value for cash_user.live_city
     *
     * @mbg.generated
     */
    public void setLiveCity(Long liveCity) {
        this.liveCity = liveCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.live_area
     *
     * @return the value of cash_user.live_area
     *
     * @mbg.generated
     */
    public Long getLiveArea() {
        return liveArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.live_area
     *
     * @param liveArea the value for cash_user.live_area
     *
     * @mbg.generated
     */
    public void setLiveArea(Long liveArea) {
        this.liveArea = liveArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.live_address
     *
     * @return the value of cash_user.live_address
     *
     * @mbg.generated
     */
    public String getLiveAddress() {
        return liveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.live_address
     *
     * @param liveAddress the value for cash_user.live_address
     *
     * @mbg.generated
     */
    public void setLiveAddress(String liveAddress) {
        this.liveAddress = liveAddress == null ? null : liveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.household_address
     *
     * @return the value of cash_user.household_address
     *
     * @mbg.generated
     */
    public String getHouseholdAddress() {
        return householdAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.household_address
     *
     * @param householdAddress the value for cash_user.household_address
     *
     * @mbg.generated
     */
    public void setHouseholdAddress(String householdAddress) {
        this.householdAddress = householdAddress == null ? null : householdAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.unit_name
     *
     * @return the value of cash_user.unit_name
     *
     * @mbg.generated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.unit_name
     *
     * @param unitName the value for cash_user.unit_name
     *
     * @mbg.generated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.unit_province
     *
     * @return the value of cash_user.unit_province
     *
     * @mbg.generated
     */
    public Long getUnitProvince() {
        return unitProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.unit_province
     *
     * @param unitProvince the value for cash_user.unit_province
     *
     * @mbg.generated
     */
    public void setUnitProvince(Long unitProvince) {
        this.unitProvince = unitProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.unit_city
     *
     * @return the value of cash_user.unit_city
     *
     * @mbg.generated
     */
    public Long getUnitCity() {
        return unitCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.unit_city
     *
     * @param unitCity the value for cash_user.unit_city
     *
     * @mbg.generated
     */
    public void setUnitCity(Long unitCity) {
        this.unitCity = unitCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.unit_area
     *
     * @return the value of cash_user.unit_area
     *
     * @mbg.generated
     */
    public Long getUnitArea() {
        return unitArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.unit_area
     *
     * @param unitArea the value for cash_user.unit_area
     *
     * @mbg.generated
     */
    public void setUnitArea(Long unitArea) {
        this.unitArea = unitArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.unit_address
     *
     * @return the value of cash_user.unit_address
     *
     * @mbg.generated
     */
    public String getUnitAddress() {
        return unitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.unit_address
     *
     * @param unitAddress the value for cash_user.unit_address
     *
     * @mbg.generated
     */
    public void setUnitAddress(String unitAddress) {
        this.unitAddress = unitAddress == null ? null : unitAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.unit_mobile
     *
     * @return the value of cash_user.unit_mobile
     *
     * @mbg.generated
     */
    public String getUnitMobile() {
        return unitMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.unit_mobile
     *
     * @param unitMobile the value for cash_user.unit_mobile
     *
     * @mbg.generated
     */
    public void setUnitMobile(String unitMobile) {
        this.unitMobile = unitMobile == null ? null : unitMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.zm_score
     *
     * @return the value of cash_user.zm_score
     *
     * @mbg.generated
     */
    public String getZmScore() {
        return zmScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.zm_score
     *
     * @param zmScore the value for cash_user.zm_score
     *
     * @mbg.generated
     */
    public void setZmScore(String zmScore) {
        this.zmScore = zmScore == null ? null : zmScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.zm_score_time
     *
     * @return the value of cash_user.zm_score_time
     *
     * @mbg.generated
     */
    public Date getZmScoreTime() {
        return zmScoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.zm_score_time
     *
     * @param zmScoreTime the value for cash_user.zm_score_time
     *
     * @mbg.generated
     */
    public void setZmScoreTime(Date zmScoreTime) {
        this.zmScoreTime = zmScoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.zm_open_id
     *
     * @return the value of cash_user.zm_open_id
     *
     * @mbg.generated
     */
    public String getZmOpenId() {
        return zmOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.zm_open_id
     *
     * @param zmOpenId the value for cash_user.zm_open_id
     *
     * @mbg.generated
     */
    public void setZmOpenId(String zmOpenId) {
        this.zmOpenId = zmOpenId == null ? null : zmOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.authentication_flag
     *
     * @return the value of cash_user.authentication_flag
     *
     * @mbg.generated
     */
    public Byte getAuthenticationFlag() {
        return authenticationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.authentication_flag
     *
     * @param authenticationFlag the value for cash_user.authentication_flag
     *
     * @mbg.generated
     */
    public void setAuthenticationFlag(Byte authenticationFlag) {
        this.authenticationFlag = authenticationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.ocr_flag
     *
     * @return the value of cash_user.ocr_flag
     *
     * @mbg.generated
     */
    public Byte getOcrFlag() {
        return ocrFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.ocr_flag
     *
     * @param ocrFlag the value for cash_user.ocr_flag
     *
     * @mbg.generated
     */
    public void setOcrFlag(Byte ocrFlag) {
        this.ocrFlag = ocrFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.ocr_back_flag
     *
     * @return the value of cash_user.ocr_back_flag
     *
     * @mbg.generated
     */
    public Byte getOcrBackFlag() {
        return ocrBackFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.ocr_back_flag
     *
     * @param ocrBackFlag the value for cash_user.ocr_back_flag
     *
     * @mbg.generated
     */
    public void setOcrBackFlag(Byte ocrBackFlag) {
        this.ocrBackFlag = ocrBackFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.mobile_flag
     *
     * @return the value of cash_user.mobile_flag
     *
     * @mbg.generated
     */
    public Byte getMobileFlag() {
        return mobileFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.mobile_flag
     *
     * @param mobileFlag the value for cash_user.mobile_flag
     *
     * @mbg.generated
     */
    public void setMobileFlag(Byte mobileFlag) {
        this.mobileFlag = mobileFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.face_flag
     *
     * @return the value of cash_user.face_flag
     *
     * @mbg.generated
     */
    public Byte getFaceFlag() {
        return faceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.face_flag
     *
     * @param faceFlag the value for cash_user.face_flag
     *
     * @mbg.generated
     */
    public void setFaceFlag(Byte faceFlag) {
        this.faceFlag = faceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.face_score
     *
     * @return the value of cash_user.face_score
     *
     * @mbg.generated
     */
    public String getFaceScore() {
        return faceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.face_score
     *
     * @param faceScore the value for cash_user.face_score
     *
     * @mbg.generated
     */
    public void setFaceScore(String faceScore) {
        this.faceScore = faceScore == null ? null : faceScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.online_duration
     *
     * @return the value of cash_user.online_duration
     *
     * @mbg.generated
     */
    public String getOnlineDuration() {
        return onlineDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.online_duration
     *
     * @param onlineDuration the value for cash_user.online_duration
     *
     * @mbg.generated
     */
    public void setOnlineDuration(String onlineDuration) {
        this.onlineDuration = onlineDuration == null ? null : onlineDuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.operator_access_flag
     *
     * @return the value of cash_user.operator_access_flag
     *
     * @mbg.generated
     */
    public Byte getOperatorAccessFlag() {
        return operatorAccessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.operator_access_flag
     *
     * @param operatorAccessFlag the value for cash_user.operator_access_flag
     *
     * @mbg.generated
     */
    public void setOperatorAccessFlag(Byte operatorAccessFlag) {
        this.operatorAccessFlag = operatorAccessFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.account_flag
     *
     * @return the value of cash_user.account_flag
     *
     * @mbg.generated
     */
    public Byte getAccountFlag() {
        return accountFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.account_flag
     *
     * @param accountFlag the value for cash_user.account_flag
     *
     * @mbg.generated
     */
    public void setAccountFlag(Byte accountFlag) {
        this.accountFlag = accountFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.sign_fail_msg
     *
     * @return the value of cash_user.sign_fail_msg
     *
     * @mbg.generated
     */
    public String getSignFailMsg() {
        return signFailMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.sign_fail_msg
     *
     * @param signFailMsg the value for cash_user.sign_fail_msg
     *
     * @mbg.generated
     */
    public void setSignFailMsg(String signFailMsg) {
        this.signFailMsg = signFailMsg == null ? null : signFailMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.crawl_time
     *
     * @return the value of cash_user.crawl_time
     *
     * @mbg.generated
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.crawl_time
     *
     * @param crawlTime the value for cash_user.crawl_time
     *
     * @mbg.generated
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.channel_code
     *
     * @return the value of cash_user.channel_code
     *
     * @mbg.generated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.channel_code
     *
     * @param channelCode the value for cash_user.channel_code
     *
     * @mbg.generated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_login_time
     *
     * @return the value of cash_user.statistics_firts_login_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsLoginTime() {
        return statisticsFirtsLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_login_time
     *
     * @param statisticsFirtsLoginTime the value for cash_user.statistics_firts_login_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsLoginTime(Date statisticsFirtsLoginTime) {
        this.statisticsFirtsLoginTime = statisticsFirtsLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_supplement_time
     *
     * @return the value of cash_user.statistics_firts_supplement_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsSupplementTime() {
        return statisticsFirtsSupplementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_supplement_time
     *
     * @param statisticsFirtsSupplementTime the value for cash_user.statistics_firts_supplement_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsSupplementTime(Date statisticsFirtsSupplementTime) {
        this.statisticsFirtsSupplementTime = statisticsFirtsSupplementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_authentication_time
     *
     * @return the value of cash_user.statistics_firts_authentication_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsAuthenticationTime() {
        return statisticsFirtsAuthenticationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_authentication_time
     *
     * @param statisticsFirtsAuthenticationTime the value for cash_user.statistics_firts_authentication_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsAuthenticationTime(Date statisticsFirtsAuthenticationTime) {
        this.statisticsFirtsAuthenticationTime = statisticsFirtsAuthenticationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_operator_time
     *
     * @return the value of cash_user.statistics_firts_operator_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsOperatorTime() {
        return statisticsFirtsOperatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_operator_time
     *
     * @param statisticsFirtsOperatorTime the value for cash_user.statistics_firts_operator_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsOperatorTime(Date statisticsFirtsOperatorTime) {
        this.statisticsFirtsOperatorTime = statisticsFirtsOperatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_face_time
     *
     * @return the value of cash_user.statistics_firts_face_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsFaceTime() {
        return statisticsFirtsFaceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_face_time
     *
     * @param statisticsFirtsFaceTime the value for cash_user.statistics_firts_face_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsFaceTime(Date statisticsFirtsFaceTime) {
        this.statisticsFirtsFaceTime = statisticsFirtsFaceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_sign_time
     *
     * @return the value of cash_user.statistics_firts_sign_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsSignTime() {
        return statisticsFirtsSignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_sign_time
     *
     * @param statisticsFirtsSignTime the value for cash_user.statistics_firts_sign_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsSignTime(Date statisticsFirtsSignTime) {
        this.statisticsFirtsSignTime = statisticsFirtsSignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_apply_time
     *
     * @return the value of cash_user.statistics_firts_apply_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsApplyTime() {
        return statisticsFirtsApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_apply_time
     *
     * @param statisticsFirtsApplyTime the value for cash_user.statistics_firts_apply_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsApplyTime(Date statisticsFirtsApplyTime) {
        this.statisticsFirtsApplyTime = statisticsFirtsApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_auto_time
     *
     * @return the value of cash_user.statistics_firts_auto_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsAutoTime() {
        return statisticsFirtsAutoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_auto_time
     *
     * @param statisticsFirtsAutoTime the value for cash_user.statistics_firts_auto_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsAutoTime(Date statisticsFirtsAutoTime) {
        this.statisticsFirtsAutoTime = statisticsFirtsAutoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_obtain_time
     *
     * @return the value of cash_user.statistics_firts_obtain_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsObtainTime() {
        return statisticsFirtsObtainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_obtain_time
     *
     * @param statisticsFirtsObtainTime the value for cash_user.statistics_firts_obtain_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsObtainTime(Date statisticsFirtsObtainTime) {
        this.statisticsFirtsObtainTime = statisticsFirtsObtainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_loan_time
     *
     * @return the value of cash_user.statistics_firts_loan_time
     *
     * @mbg.generated
     */
    public Date getStatisticsFirtsLoanTime() {
        return statisticsFirtsLoanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_loan_time
     *
     * @param statisticsFirtsLoanTime the value for cash_user.statistics_firts_loan_time
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsLoanTime(Date statisticsFirtsLoanTime) {
        this.statisticsFirtsLoanTime = statisticsFirtsLoanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.statistics_firts_loan_amount
     *
     * @return the value of cash_user.statistics_firts_loan_amount
     *
     * @mbg.generated
     */
    public BigDecimal getStatisticsFirtsLoanAmount() {
        return statisticsFirtsLoanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.statistics_firts_loan_amount
     *
     * @param statisticsFirtsLoanAmount the value for cash_user.statistics_firts_loan_amount
     *
     * @mbg.generated
     */
    public void setStatisticsFirtsLoanAmount(BigDecimal statisticsFirtsLoanAmount) {
        this.statisticsFirtsLoanAmount = statisticsFirtsLoanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.status
     *
     * @return the value of cash_user.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.status
     *
     * @param status the value for cash_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.is_credit
     *
     * @return the value of cash_user.is_credit
     *
     * @mbg.generated
     */
    public Integer getIsCredit() {
        return isCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.is_credit
     *
     * @param isCredit the value for cash_user.is_credit
     *
     * @mbg.generated
     */
    public void setIsCredit(Integer isCredit) {
        this.isCredit = isCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.credit_amount
     *
     * @return the value of cash_user.credit_amount
     *
     * @mbg.generated
     */
    public BigDecimal getCreditAmount() {
        return creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.credit_amount
     *
     * @param creditAmount the value for cash_user.credit_amount
     *
     * @mbg.generated
     */
    public void setCreditAmount(BigDecimal creditAmount) {
        this.creditAmount = creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.first_credit_amount
     *
     * @return the value of cash_user.first_credit_amount
     *
     * @mbg.generated
     */
    public BigDecimal getFirstCreditAmount() {
        return firstCreditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.first_credit_amount
     *
     * @param firstCreditAmount the value for cash_user.first_credit_amount
     *
     * @mbg.generated
     */
    public void setFirstCreditAmount(BigDecimal firstCreditAmount) {
        this.firstCreditAmount = firstCreditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.is_enabled
     *
     * @return the value of cash_user.is_enabled
     *
     * @mbg.generated
     */
    public Byte getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.is_enabled
     *
     * @param isEnabled the value for cash_user.is_enabled
     *
     * @mbg.generated
     */
    public void setIsEnabled(Byte isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.create_id
     *
     * @return the value of cash_user.create_id
     *
     * @mbg.generated
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.create_id
     *
     * @param createId the value for cash_user.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.create_time
     *
     * @return the value of cash_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.create_time
     *
     * @param createTime the value for cash_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.modify_id
     *
     * @return the value of cash_user.modify_id
     *
     * @mbg.generated
     */
    public Long getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.modify_id
     *
     * @param modifyId the value for cash_user.modify_id
     *
     * @mbg.generated
     */
    public void setModifyId(Long modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.modify_time
     *
     * @return the value of cash_user.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.modify_time
     *
     * @param modifyTime the value for cash_user.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.credit_time
     *
     * @return the value of cash_user.credit_time
     *
     * @mbg.generated
     */
    public Date getCreditTime() {
        return creditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.credit_time
     *
     * @param creditTime the value for cash_user.credit_time
     *
     * @mbg.generated
     */
    public void setCreditTime(Date creditTime) {
        this.creditTime = creditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.zm_flag
     *
     * @return the value of cash_user.zm_flag
     *
     * @mbg.generated
     */
    public Integer getZmFlag() {
        return zmFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.zm_flag
     *
     * @param zmFlag the value for cash_user.zm_flag
     *
     * @mbg.generated
     */
    public void setZmFlag(Integer zmFlag) {
        this.zmFlag = zmFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cash_user.openid
     *
     * @return the value of cash_user.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cash_user.openid
     *
     * @param openid the value for cash_user.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}